name: astropy-dev
dependencies:
- appnope=0.1.0=py34_0
- astropy=1.0.4=np19py34_0
- certifi=14.05.14=py34_0
- decorator=4.0.2=py34_0
- ipykernel=4.0.3=py34_0
- ipython=4.0.0=py34_1
- ipython-notebook=4.0.4=py34_0
- ipython_genutils=0.1.0=py34_0
- jinja2=2.8=py34_0
- jsonschema=2.4.0=py34_0
- jupyter_client=4.0.0=py34_0
- jupyter_core=4.0.6=py34_0
- libsodium=0.4.5=0
- markupsafe=0.23=py34_0
- mistune=0.7.1=py34_0
- nbconvert=4.0.0=py34_0
- nbformat=4.0.0=py34_0
- notebook=4.0.4=py34_0
- numpy=1.9.3=py34_0
- openssl=1.0.1k=1
- path.py=8.1.1=py34_0
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pip=7.1.2=py34_0
- ptyprocess=0.4=py34_0
- pygments=2.0.2=py34_0
- python=3.4.3=0
- python.app=1.2=py34_4
- pyzmq=14.7.0=py34_0
- readline=6.2=2
- setuptools=18.1=py34_0
- simplegeneric=0.8.1=py34_0
- sqlite=3.8.4.1=1
- terminado=0.5=py34_0
- tk=8.5.18=0
- tornado=4.2.1=py34_0
- traitlets=4.0.0=py34_0
- wheel=0.26.0=py34_0
- xz=5.0.5=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.0.0
  - jupyter-core==4.0.6

